---
name: Unassign Stale OSCP Issues

on:
  workflow_call:
jobs:
  unassign-stale-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: boundfoxstudios/action-unassign-contributor-after-days-of-inactivity@eb02181edb32aa5eeff8e0979871d31399cf63a0 # main
        with:
          last-activity: 7
          labels: "OSCP,good first issue"
          message: '由于您未能在规定时间内完成任务，该任务已重新开放认领。如需继续完成，请重新认领；同时也欢迎其他开发者参与认领。\n\nAs the task was not completed within the specified time, it has been unassigned for claiming. If you wish to continue working on it, please reclaim the task. Other developers are also welcome to claim it.'
      - uses: boundfoxstudios/action-unassign-contributor-after-days-of-inactivity@eb02181edb32aa5eeff8e0979871d31399cf63a0 # main
        with:
          last-activity: 28
          labels: "OSCP,intermediate"
          message: '由于您未能在规定时间内完成任务，该任务已重新开放认领。如需继续完成，请重新认领；同时也欢迎其他开发者参与认领。\n\nAs the task was not completed within the specified time, it has been unassigned for claiming. If you wish to continue working on it, please reclaim the task. Other developers are also welcome to claim it.'
      - uses: boundfoxstudios/action-unassign-contributor-after-days-of-inactivity@eb02181edb32aa5eeff8e0979871d31399cf63a0 # main
        with:
          last-activity: 49
          labels: "OSCP,challenge"
          message: '由于您未能在规定时间内完成任务，该任务已重新开放认领。如需继续完成，请重新认领；同时也欢迎其他开发者参与认领。\n\nAs the task was not completed within the specified time, it has been unassigned for claiming. If you wish to continue working on it, please reclaim the task. Other developers are also welcome to claim it.'
